# -*- coding: utf-8 -*-
"""Ejercicio_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19U_7ay5i3rqfnvAfLIYuhBaS4GW264f6
"""

#   Codigo que implementa un esquema numerico
#   para determinar la precision de una maquina
#
#           Autor:
#   Angel Gilberto Carbajal Lopez
#   carbajalsecundaria@gmail.com
#   Version 2.0 : 06/02/2025
#






import numpy as np
import matplotlib.pyplot as plt

# Importamos las librerías necesarias: numpy para cálculos numéricos y matplotlib.pyplot para generar gráficas en 2D.


epsilon = 1.0  # Inicializamos epsilon con 1.0, este valor se reducirá progresivamente dividiéndolo entre 2.
iteracion = 0   # Contador que nos servirá para registrar cuántas veces hemos dividido epsilon.
epsilons = []   # Lista vacía donde almacenaremos los valores de epsilon en cada iteración.
iteraciones = [] # Lista vacía para registrar el número de iteración correspondiente.

# Iniciamos un bucle que continuará hasta que sumar epsilon a 1.0 ya no afecte el resultado.
while 1.0 + epsilon != 1.0:
    epsilon /= 2  # Reducimos epsilon a la mitad en cada paso.
    iteracion += 1  # Incrementamos el contador de iteraciones.
    iteraciones.append(iteracion)  # Guardamos la iteración actual en la lista.
    epsilons.append(epsilon)  # Guardamos el valor de epsilon en la lista.

    print(f"Iteración: {iteracion}, Precisión de máquina: {epsilon}")  # Mostramos los valores en cada iteración.

# Duplicamos el último valor de epsilon, ya que la última iteración lo redujo más allá del límite de precisión.
epsilon *= 2
print(f"Precisión de máquina final: {epsilon}")  # Mostramos la precisión final alcanzada por la máquina.

# Generamos la gráfica de la evolución de epsilon.
plt.figure()  # Creamos una nueva figura para la gráfica.
plt.plot(iteraciones, epsilons, label='Epsilon', marker='o')  # Dibujamos la curva con marcadores en cada punto.
plt.xscale('linear')  # Definimos una escala lineal para el eje x.
plt.yscale('linear')  # Definimos una escala lineal para el eje y.
plt.xlabel('Iteraciones')  # Etiqueta para el eje x.
plt.ylabel('Epsilon')  # Etiqueta para el eje y.
plt.legend()  # Agregamos una leyenda a la gráfica.
plt.title('Evolución de la Precisión de Máquina')  # Asignamos un título a la gráfica.
plt.show()  # Mostramos la gráfica en pantalla.

